"""Path helpers for local and cluster runs."""
from __future__ import annotations

import os
from pathlib import Path


def daycent_root() -> str:
    """Repository root, overridable for copied checkouts."""
    return os.environ.get(
        "DAYCENT_ROOT",
        str(Path(__file__).resolve().parents[2]),
    )


def output_root() -> str:
    """Root for experiment outputs."""
    return os.environ.get(
        "DAYCENT_OUTPUT_ROOT",
        os.path.join(daycent_root(), "output"),
    )


def processed_root() -> str:
    """Root for processed/cache data generated by experiments."""
    return os.environ.get(
        "DAYCENT_PROCESSED_ROOT",
        os.path.join(daycent_root(), "data"),
    )


def selection_output_root() -> str:
    """Root for selection experiment outputs."""
    return os.environ.get(
        "DAYCENT_SELECTION_OUTPUT_ROOT",
        os.path.join(output_root(), "selection"),
    )
